Add an h at the start of the value of final_snapshot_identifier if needed to make sure it starts with a letter.
This deals with the following error:
```
 Error: invalid value for final_snapshot_identifier (must begin with alphabetic character)
│
│   with aws_db_instance.infrastructure_rds["app"],
│   on rds-infrastructure-instance.tf line 65, in resource "aws_db_instance" "infrastructure_rds":
│   65:   final_snapshot_identifier = "${local.resource_prefix_hash}-${each.key}-final"
```